### ISSUE TITLE
Small desktop resolution does not slide

### ISSUE THREAD

**Issue by savonije** [YourSurpriseCom/slider#65]
**Pattern:**
Resize your window to a < 997 pixels.
When dragging the slider it sticks to your mouse and shows some unexpected behaviour.

https://github.com/YourSurpriseCom/slider/assets/12546104/5c12d7b9-4b31-4c02-865c-be51a50ae591

**Comment by iFiz** [comment]
Hi Kevin!

What you're seeing is the image being grabbed natively by the browser instead of the slider. In this case the image should be given the '[draggable](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/draggable)' property, which should be set to false. This will instruct the browser that the image can't be dragged.

Right now it's the responsibility of the user to set the draggable property of the slides. 

```
<Slider>
 <img draggable="false"/>
</Slider>
```

The idea behind the slider is that's it's essentially just a wrapper, where the user is responsible for the rest of the implementation. However, I can't really think of a use case where it's desired to have a draggable image within a slider, so maybe the Slider should automatically add this property. What are your thoughts on this?
